# CMake generated Testfile for 
# Source directory: /home/prog/Документы/libiec61850-1.611/examples
# Build directory: /home/prog/Документы/libiec61850-1.611/examples/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
subdirs("server_example_simple")
subdirs("server_example_basic_io")
subdirs("server_example_password_auth")
subdirs("server_example_write_handler")
subdirs("server_example_control")
subdirs("server_example_dynamic")
subdirs("server_example_config_file")
subdirs("server_example_complex_array")
subdirs("server_example_threadless")
subdirs("server_example_61400_25")
subdirs("server_example_setting_groups")
subdirs("server_example_logging")
subdirs("server_example_files")
subdirs("server_example_substitution")
subdirs("server_example_service_tracking")
subdirs("server_example_deadband")
subdirs("server_example_access_control")
subdirs("iec61850_client_example1")
subdirs("iec61850_client_example2")
subdirs("iec61850_client_example_control")
subdirs("iec61850_client_example4")
subdirs("iec61850_client_example5")
subdirs("iec61850_client_example_reporting")
subdirs("iec61850_client_example_log")
subdirs("iec61850_client_example_array")
subdirs("iec61850_client_example_files")
subdirs("iec61850_client_example_async")
subdirs("iec61850_client_file_async")
subdirs("iec61850_client_example_rcbAsync")
subdirs("iec61850_client_example_ClientGooseControl")
subdirs("iec61850_client_example_ClientGooseControlAsync")
subdirs("mms_utility")
subdirs("server_example_goose")
subdirs("goose_observer")
subdirs("goose_subscriber")
subdirs("goose_publisher")
subdirs("sv_subscriber")
subdirs("iec61850_9_2_LE_example")
subdirs("iec61850_sv_client_example")
subdirs("sv_publisher")
